name: 1. Infrastructure Deployment

on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'apply or destroy'
        required: true
        default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Checkov IaC Scan (report only - does not block)
        run: |
          docker run --rm -v $(pwd):/tf bridgecrew/checkov \
            -d /tf --output json > checkov-report.json || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54531c595abb0b4305a1c73e0f3ff50d8eda  # v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808  # v4.3.3
        with:
          name: tfplan
          path: terraform/tfplan

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve tfplan
          fi